//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDeanery.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ambion
    {
        public Ambion()
        {
            this.ArarkaAmbion = new HashSet<ArarkaAmbion>();
            this.FakultetArarka = new HashSet<FakultetArarka>();
        }
    
        public int AmbionID { get; set; }
        public string AmbionAnun { get; set; }
    
        public virtual ICollection<ArarkaAmbion> ArarkaAmbion { get; set; }
        public virtual ICollection<FakultetArarka> FakultetArarka { get; set; }
    }
}
