//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDeanery.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArarkaAmbion
    {
        public int ID { get; set; }
        public Nullable<int> AmbionID { get; set; }
        public string Ambion { get; set; }
        public Nullable<int> ArarkaID { get; set; }
        public string ArarkaAnun { get; set; }
    
        public virtual Ambion Ambion1 { get; set; }
        public virtual Ararka Ararka { get; set; }
    }
}
