//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDeanery.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacakaShabat
    {
        public int ID { get; set; }
        public string StudentCode { get; set; }
        public int ArarkaID { get; set; }
        public int Kurs { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> Ndanur { get; set; }
        public string ErkuSh { get; set; }
        public string ErekSh { get; set; }
        public string ChorSh { get; set; }
        public string HingSh { get; set; }
        public string Urbat { get; set; }
        public string Shabat { get; set; }
        public string Kiraki { get; set; }
    
        public virtual Ararka Ararka { get; set; }
        public virtual Student Student { get; set; }
    }
}
