//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDeanery.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masnagitucyun
    {
        public int MasnagitutyunID { get; set; }
        public string Masnagitutyun { get; set; }
        public string MasnagitutyunKrchat { get; set; }
    }
}
