//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDeanery.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public long StudentID { get; set; }
        public string StudentCode { get; set; }
        public string Azganun { get; set; }
        public string Anun { get; set; }
        public string Hayranun { get; set; }
        public string Ser { get; set; }
        public Nullable<System.DateTime> Bithday { get; set; }
        public string Tcnndavayr { get; set; }
        public string Qaxaqaciutyun { get; set; }
        public string Incheavartel_dproc_ { get; set; }
        public Nullable<int> AvarteluTarin__dproc_ { get; set; }
        public string AvartakanVkayakaniHamar { get; set; }
        public string BnakutyanVayr { get; set; }
        public string GrancmanVayr { get; set; }
        public string Herbjayin { get; set; }
        public string Mail { get; set; }
        public Nullable<int> YndunveluTarin { get; set; }
        public string HramanTiv { get; set; }
        public Nullable<System.DateTime> HramaniOrAmisTari { get; set; }
        public Nullable<bool> UsucmanDzev { get; set; }
        public Nullable<bool> YndAvartel { get; set; }
        public string StugmanGrquyk { get; set; }
        public Nullable<int> AvarteluTarin { get; set; }
        public byte[] Nkar { get; set; }
    }
}
