//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDeanery.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.BacakaShabat = new HashSet<BacakaShabat>();
        }
    
        public long StudentID { get; set; }
        public string StudentCode { get; set; }
        public string Azganun { get; set; }
        public string Anun { get; set; }
        public string Hayranun { get; set; }
        public string Ser { get; set; }
        public Nullable<System.DateTime> Bithday { get; set; }
        public string Tcnndavayr { get; set; }
        public string Qaxaqaciutyun { get; set; }
        public string Incheavartel_dproc_ { get; set; }
        public Nullable<int> AvarteluTarin__dproc_ { get; set; }
        public string AvartakanVkayakaniHamar { get; set; }
        public string BnakutyanVayr { get; set; }
        public string GrancmanVayr { get; set; }
        public string Herbjayin { get; set; }
        public string Mail { get; set; }
        public Nullable<int> YndunveluTarin { get; set; }
        public string HramanTiv { get; set; }
        public Nullable<System.DateTime> HramaniOrAmisTari { get; set; }
        public Nullable<bool> UsucmanDzev { get; set; }
        public Nullable<bool> YndAvartel { get; set; }
        public string StugmanGrquyk { get; set; }
        public Nullable<int> AvarteluTarin { get; set; }
        public byte[] Nkar { get; set; }
    
        public virtual ICollection<BacakaShabat> BacakaShabat { get; set; }
    }
}
