//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDeanery.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversityEntities : DbContext
    {
        public UniversityEntities()
            : base("name=UniversityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ambion> Ambion { get; set; }
        public DbSet<Ararka> Ararka { get; set; }
        public DbSet<ArarkaAmbion> ArarkaAmbion { get; set; }
        public DbSet<Fakultet> Fakultet { get; set; }
        public DbSet<FakultetArarka> FakultetArarka { get; set; }
        public DbSet<Masnagitucyun> Masnagitucyun { get; set; }
        public DbSet<Student> Student { get; set; }
    }
}
