//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDeanery.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class UniversityEntities : DbContext
    {
        public UniversityEntities()
            : base("name=UniversityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ambion> Ambion { get; set; }
        public DbSet<Ararka> Ararka { get; set; }
        public DbSet<ArarkaAmbion> ArarkaAmbion { get; set; }
        public DbSet<Fakultet> Fakultet { get; set; }
        public DbSet<FakultetArarka> FakultetArarka { get; set; }
        public DbSet<Masnagitucyun> Masnagitucyun { get; set; }
        public DbSet<Student> Student { get; set; }
    
        public virtual ObjectResult<GetStudentCode_Result> GetStudentCode(string text)
        {
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStudentCode_Result>("GetStudentCode", textParameter);
        }
    }
}
